# Generated by Django 3.2.3 on 2021-06-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('prodpriceunit', models.CharField(choices=[('1 kg', '1 Kg'), ('1 piece', '1 Piece'), ('1 bunch', '1 Bunch'), ('100 mg', '100 mg')], default='1 Kg', max_length=20)),
                ('prodprice', models.IntegerField()),
                ('prodstock', models.IntegerField()),
                ('prodcategory', models.CharField(max_length=100)),
                ('addondate', models.DateTimeField()),
                ('prodoffer', models.BooleanField(default=False)),
                ('prodofferdetails', models.TextField()),
                ('prodimage', models.ImageField(upload_to='product images')),
                ('prodselected', models.IntegerField(default=0)),
            ],
        ),
    ]
