# Generated by Django 3.2.8 on 2021-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_main', '0002_auto_20210705_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
