# Generated by Django 3.2.3 on 2021-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
