# Generated by Django 3.1.5 on 2021-07-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_main', '0002_auto_20210705_2107'),
        ('customer_activity', '0003_auto_20210702_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='prodname',
        ),
        migrations.RemoveField(
            model_name='cart_items',
            name='prodprice',
        ),
        migrations.RemoveField(
            model_name='cart_items',
            name='prodpriceunit',
        ),
        migrations.RemoveField(
            model_name='cart_items',
            name='username',
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_main.productdetails'),
        ),
    ]
