# Generated by Django 3.1.5 on 2021-07-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0004_auto_20210705_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
