# Generated by Django 3.1.5 on 2021-07-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_main', '0002_auto_20210705_2107'),
        ('customer_activity', '0006_orderlist_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_main.productdetails')),
            ],
        ),
    ]
