# Generated by Django 3.1.5 on 2021-07-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0007_wishlist_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Order_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('deliver_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('town', models.CharField(max_length=30)),
                ('postcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('order_notes', models.TextField()),
                ('total_price', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], max_length=20)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_activity.orderlist_details')),
            ],
        ),
    ]
