# Generated by Django 3.1.5 on 2021-07-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0010_auto_20210725_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_order_table',
            name='no_of_products',
            field=models.IntegerField(null=True),
        ),
    ]
