# Generated by Django 3.1.5 on 2021-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0012_auto_20210726_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_order_table',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], max_length=20),
        ),
    ]
