# Generated by Django 3.1.5 on 2021-07-31 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0013_auto_20210729_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_order_table',
            name='deliver_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderlist_details',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 21, 10, 12, 109783)),
        ),
    ]
